<h2>Agregar tarea</h2>

<form action="<?php echo APP_URL."tareas/agregar"; ?>" method="POST" accept-charset="utf-8">
	
	<table border="1">
	<tr height="50">
	<td>
	<label for="nombre">Nombre</label>
	<input type="text" name="nombre">
	</td>
	</tr>
	
	<tr height="50">
	<td>
	<label for="descripcion">Descripcion</label>
	<textarea name="descripcion"></textarea>
	</td>
	</tr>
	
	<tr height="50">
	<td>
	<label for="fecha">Fecha</label>
	<input type="date" name="fecha" value="<?php echo date("Y-m-d"); ?> ">
	</td>
	</tr>
	
	<tr height="50">
	<td>
	<label for="prioridad">Prioridad</label>
	<input type="range" name="prioridad" min="0" max="10">
	</td>
	</tr>
	
	<tr height="50">
	<td>
	<label for="categoria">Categoría</label>
	<select name="categoria_id">
		<?php foreach ($this->categorias as $categoria) { ?>
			<option value="<?php echo $categoria["id"]; ?>">
				<?php echo $categoria["nombre"]; ?></option>
		<?php } ?>
	</select>
	</td>
	</tr>
	
	<!--<input type="submit" value="Guardar tarea">-->
	<td class="center-align">
		<button class="btn waves-effect waves-light" type="submit"><i class="material-icons right" >cloud</i>Guardar</button>
	</td>
	</table>
	</tr>
</form>