<h2>Editar tarea</h2>

<form action="<?php echo APP_URL."tareas/editar"; ?>" method="POST" accept-charset="utf-8">
	
	
	<label for="id">ID</label>
	<input type="hidden" name="id" value="<?php echo $this->tarea["id"]; ?>">
	

	
	<label for="nombre">Nombre</label>
	<input type="text" name="nombre" value="<?php echo $this->tarea["nombre"]; ?>">
	
	
	
	<label for="descripcion">Descripcion</label>
	<textarea name="descripcion"><?php echo $this->tarea["descripcion"]; ?></textarea>
	
	
	
	<label for="fecha">Fecha</label>
	<input type="date" name="fecha" value="<?php echo $this->tarea["fecha"]; ?>">
	
	
	
	<label for="prioridad">Prioridad</label>
	<input type="range" name="prioridad" min="0" max="10">
	
	<label for="categoria">Categoría</label>
	<select name="categoria_id">
		<?php foreach ($this->categorias as $categoria) { 
			if ($this->tarea["categoria_id"]==$categoria["id"]) { ?>
				<option select value="<?php echo $categoria["id"]; ?>">
				<?php echo $categoria["nombre"]; ?></option>
		<?php }else{ ?>
				<option value="<?php echo $categoria["id"]; ?>">
				<?php echo $categoria["nombre"]; ?></option>
		<?php
			
			}
		}
		  ?>
	</select>
	
	
	<!--<input type="submit" value="Guardar tarea">-->
	<td class="center-align">
		<button class="btn waves-effect waves-light" type="submit"><i class="material-icons">sync</i>Actualizar</button>
	</td>

	
</form>